### ISSUE TITLE
v2 not working anymore

### ISSUE THREAD

**Issue by santah** [KyranRana/cloudflare-bypass#62] opened 2018-05-29 09:12 UTC
Edit: This is via CFCurl, with CFStreamContext - it works fine.

Since the 23rd of May, v2 can't seem to be able to bypass cloudflare anymore.

The url I'm trying is: https://predb.me/ and outputting the browser check page (instead of the target page, as it successfully did for the last few months).

I don't really know how to debug further. Let me know.

**Comment by railken** [comment] 2018-05-29 12:30
The primary goal of this library is to bypass this:

![example](https://i.imgur.com/WYBvXZj.png)

In your case there is nothing to bypass, only a simple header agent to add

Simple request return 503
```
curl -X GET 'https://predb.me/'
```

Using User-Agent return 200
```
curl -X GET \
  https://predb.me/ \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36'
```
If your ip got banned  you should change your ip or use a proxy library

Hopefully this will help to clarify

**Comment by santah** [comment] 2018-05-29 13:20
It's possible it depends on country (I'm accessing it from the UK).

Even with user-agent, I get the "Please wait 5 seconds" browser check which before 23rd of May was successfully bypassed by the same php class.

The IP doesn't seem to be banned or in anyway specifically restricted as it pulls the target page just fine using CFStreamContext.

**Comment by railken** [comment] 2018-05-29 15:06
Yes, it's possible!

If you see the "Please wait 5 seconds" than we have a problem.

I have tried with a bunch of proxies from uk, but i still get 200

```
curl -X GET \
  https://predb.me/ \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36' \
  --proxy tcp://185.6.197.82:3128
```

**Comment by santah** [comment] 2018-05-30 04:44
here:

```
* Added cookie cf_clearance="fd7504bf4550bdafa2a75a1e1f9f2023d4145521-1527655355-604800" for domain (nil), path (nil), expire 0
* Added cookie __cfduid="d5a6b286685c742fef1ad99eaa9ea768a1527655351" for domain (nil), path (nil), expire 0
*   Trying 104.18.61.235...
* TCP_NODELAY set
* Connected to predb.me (104.18.61.235) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=sni188534.cloudflaressl.com
*  start date: May 13 00:00:00 2018 GMT
*  expire date: Nov 19 23:59:59 2018 GMT
*  subjectAltName: host "predb.me" matched cert's "predb.me"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok.
> GET /?search=720p+cat%3A-tv-hd%2C-xxx+-s01*+-s02*+-s03*+-s04*+-s05*+-s06*+-s07*+-s08*+-s09*+-s10*+-s11*+-s12*+-s13*+-s14*+-s15*+-s16*+-s17*+-s18*+-s19*+-s20*+-s21*+-s22*+-s23*+-s24*+-s25*&page=1 HTTP/1.1

Host: predb.me

User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

Accept: */*



< HTTP/1.1 503 Service Temporarily Unavailable

< Date: Wed, 30 May 2018 04:43:24 GMT

< Content-Type: text/html; charset=UTF-8

< Transfer-Encoding: chunked

< Connection: close

* Added cookie __cfduid="daf031cd1eb6662c3b7ba606fcd5e3ec31527655404" for domain predb.me, path /, expire 1559191404
< Set-Cookie: __cfduid=daf031cd1eb6662c3b7ba606fcd5e3ec31527655404; expires=Thu, 30-May-19 04:43:24 GMT; path=/; domain=.predb.me; HttpOnly

< X-Frame-Options: SAMEORIGIN

< Cache-Control: no-cache

< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"

< Server: cloudflare

< CF-RAY: 422e8a27fb086a07-LHR

< 

* Closing connection 0
* Replaced cookie cf_clearance="13350c64d5ee86ea897dbe0a3fa14dc2b642a95d-1527655408-604800" for domain (nil), path (nil), expire 0
* Replaced cookie __cfduid="dcd130283610061a35da53b410f1e84341527655404" for domain (nil), path (nil), expire 0
* Hostname predb.me was found in DNS cache
*   Trying 104.18.61.235...
* TCP_NODELAY set
* Connected to predb.me (104.18.61.235) port 443 (#1)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL re-using session ID
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=sni188534.cloudflaressl.com
*  start date: May 13 00:00:00 2018 GMT
*  expire date: Nov 19 23:59:59 2018 GMT
*  subjectAltName: host "predb.me" matched cert's "predb.me"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok.
> GET /?search=720p+cat%3A-tv-hd%2C-xxx+-s01*+-s02*+-s03*+-s04*+-s05*+-s06*+-s07*+-s08*+-s09*+-s10*+-s11*+-s12*+-s13*+-s14*+-s15*+-s16*+-s17*+-s18*+-s19*+-s20*+-s21*+-s22*+-s23*+-s24*+-s25*&page=1 HTTP/1.1

Host: predb.me

User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

Accept: */*

Cookie: __cfduid=daf031cd1eb6662c3b7ba606fcd5e3ec31527655404



< HTTP/1.1 503 Service Temporarily Unavailable

< Date: Wed, 30 May 2018 04:43:29 GMT

< Content-Type: text/html; charset=UTF-8

< Transfer-Encoding: chunked

< Connection: close

< X-Frame-Options: SAMEORIGIN

< Cache-Control: no-cache

< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"

< Server: cloudflare

< CF-RAY: 422e8a430acf0a7e-LHR

< 

* Closing connection 1

```

**Comment by KyranRana** [comment] 2018-06-02 08:07
I'll merge as soon as its confirmed a working fix. Really do appreciate the support you are giving here @railken

**Comment by santah** [comment] 2018-06-02 14:00
Sorry for the delay! Unfortunately, still getting the 5 seconds page. Log again below:

`* Added cookie cf_clearance="6b9bb0c172264177abe41467e341b862a7b3b00f-1527947815-604800" for domain (nil), path (nil), expire 0
* Added cookie __cfduid="dfcd37d799435f03caf8e3b1c14eec8c91527947811" for domain (nil), path (nil), expire 0
*   Trying 104.18.60.235...
* TCP_NODELAY set
* Connected to predb.me (104.18.60.235) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=sni188534.cloudflaressl.com
*  start date: May 13 00:00:00 2018 GMT
*  expire date: Nov 19 23:59:59 2018 GMT
*  subjectAltName: host "predb.me" matched cert's "predb.me"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok.
> GET /?search=720p+cat%3A-tv-hd%2C-xxx+-s01*+-s02*+-s03*+-s04*+-s05*+-s06*+-s07*+-s08*+-s09*+-s10*+-s11*+-s12*+-s13*+-s14*+-s15*+-s16*+-s17*+-s18*+-s19*+-s20*+-s21*+-s22*+-s23*+-s24*+-s25*&page=1 HTTP/1.1

Host: predb.me

User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

Accept: */*



< HTTP/1.1 503 Service Temporarily Unavailable

< Date: Sat, 02 Jun 2018 13:58:46 GMT

< Content-Type: text/html; charset=UTF-8

< Transfer-Encoding: chunked

< Connection: close

* Added cookie __cfduid="db629b73b957399570e6cc403d34941e41527947926" for domain predb.me, path /, expire 1559483926
< Set-Cookie: __cfduid=db629b73b957399570e6cc403d34941e41527947926; expires=Sun, 02-Jun-19 13:58:46 GMT; path=/; domain=.predb.me; HttpOnly

< X-Frame-Options: SAMEORIGIN

< Cache-Control: no-cache

< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"

< Server: cloudflare

< CF-RAY: 424a6fcf5e9d6b97-LHR

< 

* Closing connection 0
* Replaced cookie cf_clearance="6dbeca28e144394cbf2f5f9526183c5afd8a95a4-1527947931-604800" for domain (nil), path (nil), expire 0
* Replaced cookie __cfduid="d24d50866321e539e716d1f1dde32e6c71527947926" for domain (nil), path (nil), expire 0
* Hostname predb.me was found in DNS cache
*   Trying 104.18.60.235...
* TCP_NODELAY set
* Connected to predb.me (104.18.60.235) port 443 (#1)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL re-using session ID
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=sni188534.cloudflaressl.com
*  start date: May 13 00:00:00 2018 GMT
*  expire date: Nov 19 23:59:59 2018 GMT
*  subjectAltName: host "predb.me" matched cert's "predb.me"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok.
> GET /?search=720p+cat%3A-tv-hd%2C-xxx+-s01*+-s02*+-s03*+-s04*+-s05*+-s06*+-s07*+-s08*+-s09*+-s10*+-s11*+-s12*+-s13*+-s14*+-s15*+-s16*+-s17*+-s18*+-s19*+-s20*+-s21*+-s22*+-s23*+-s24*+-s25*&page=1 HTTP/1.1

Host: predb.me

User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

Accept: */*

Cookie: __cfduid=db629b73b957399570e6cc403d34941e41527947926



< HTTP/1.1 503 Service Temporarily Unavailable

< Date: Sat, 02 Jun 2018 13:58:51 GMT

< Content-Type: text/html; charset=UTF-8

< Transfer-Encoding: chunked

< Connection: close

< X-Frame-Options: SAMEORIGIN

< Cache-Control: no-cache

< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"

< Server: cloudflare

< CF-RAY: 424a6fea8cfe1395-LHR

< 

* Closing connection 1
`

**Comment by railken** [comment] 2018-06-02 15:07
I know it's a dumb question, but i have to ask anyway: the commit is not merged, did you tried with the commit of the pull request or simply re-downloaded the library?


The "protection of 5 seconds" occurs only when you're searching, there is no protection in the GET /. 
Can you confirm me this?

Return 200
```
curl -X GET \
  https://predb.me/ \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36' \
  -I
```

Return 503
```
curl -X GET \
  https://predb.me/?search=anything \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36' \
  -I
```

In any case i have to add a config "verbose" to help us while debugging, otherwise it's a nightmare

**Comment by santah** [comment] 2018-06-02 15:49
I only overwrote this file, copying it from the RAW view here:

https://raw.githubusercontent.com/railken/cloudflare-bypass/79e2f46309e051f29e210b12510569df51dea261/v2/src/CloudflareBypass/CFBypass.php

Is that enough?

And yes - I confirm the "5 second" thing only pops up when searching. When simply loading predb.me - it outputs the target page.

**Comment by railken** [comment] 2018-06-02 16:58
Yes, thanks for confirming it.

I made a fix and added a config "verbose".

Please a check the same pull #63, add  `"verbose" => true` in your CFCurl instance and try again.

**Comment by santah** [comment] 2018-06-06 06:35
I've updated both CFCore and CFBypass to the latest versions.

```
<?
require 'src/autoload.php';
use CloudflareBypass\RequestMethod\CFCurl;

$url = "https://predb.me/?search=720p+cat%3A-tv-hd%2C-xxx+-s01*+-s02*+-s03*+-s04*+-s05*+-s06*+-s07*+-s08*+-s09*+-s10*+-s11*+-s12*+-s13*+-s14*+-s15*+-s16*+-s17*+-s18*+-s19*+-s20*+-s21*+-s22*+-s23*+-s24*+-s25*&page=1";


$curl_cf_wrapper = new CFCurl(array(
	'cache'         => true,  
	'max_retries'  => 5,
	'verbose'  => true
));
	
$ch = curl_init($url);
//$curl_log = fopen("curl.txt", 'w');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);

//curl_setopt($ch, CURLOPT_VERBOSE, true);
//curl_setopt($ch, CURLOPT_STDERR, $curl_log);
curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36');
$output= $curl_cf_wrapper->exec($ch);
curl_close($ch);
//echo $output;
?>
```

Here is what I'm getting as an output:

> Generated clearance link https://predb.me/cdn-cgi/l/chk_jschl?pass=1528266781.068-XfVkjgfUc%2F&jschl_vc=5e3f0bdf689ed8230e02d1200d28f576&jschl_answer=9.4570250269&search=720p+cat%3A-tv-hd%2C-xxx+-s01%2A+-s02%2A+-s03%2A+-s04%2A+-s05%2A+-s06%2A+-s07%2A+-s08%2A+-s09%2A+-s10%2A+-s11%2A+-s12%2A+-s13%2A+-s14%2A+-s15%2A+-s16%2A+-s17%2A+-s18%2A+-s19%2A+-s20%2A+-s21%2A+-s22%2A+-s23%2A+-s24%2A+-s25%2A&page=1 

Toggling "'verbose' => true" to false doesn't seem to make a difference. The output is the same.

**Comment by railken** [comment] 2018-06-07 15:39
@santah 
Working tests (PHP 7.1 and php 7.2) https://travis-ci.org/railken/cloudflare-bypass
Delete all your cache files (or disable it) and try again with #63

@nitemare 
PHP Version?
Your sample code?
Log of the request?

**Comment by santah** [comment] 2018-06-07 17:47
Updated to the latest CFBypass.

PHP Version 5.5.38

Same result. In the code I pasted before, I only changed "'cache'         => true" to false and uncommented the curl log to curl.txt.

I don't have any other cache.

Here is the log from curl:

```
*   Trying 104.18.61.235...
* TCP_NODELAY set
* Connected to predb.me (104.18.61.235) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=sni188534.cloudflaressl.com
*  start date: May 13 00:00:00 2018 GMT
*  expire date: Nov 19 23:59:59 2018 GMT
*  subjectAltName: host "predb.me" matched cert's "predb.me"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok.
> GET /?search=720p+cat%3A-tv-hd%2C-xxx+-s01*+-s02*+-s03*+-s04*+-s05*+-s06*+-s07*+-s08*+-s09*+-s10*+-s11*+-s12*+-s13*+-s14*+-s15*+-s16*+-s17*+-s18*+-s19*+-s20*+-s21*+-s22*+-s23*+-s24*+-s25*&page=1 HTTP/1.1

Host: predb.me

User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

Accept: */*



< HTTP/1.1 503 Service Temporarily Unavailable

< Date: Thu, 07 Jun 2018 17:42:34 GMT

< Content-Type: text/html; charset=UTF-8

< Transfer-Encoding: chunked

< Connection: close

< Set-Cookie: __cfduid=d7f3de32bef283f7e6f41b18058be9f6f1528393354; expires=Fri, 07-Jun-19 17:42:34 GMT; path=/; domain=.predb.me; HttpOnly

< X-Frame-Options: SAMEORIGIN

< Cache-Control: no-cache

< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"

< Server: cloudflare

< CF-RAY: 4274ea7f3d2f6a0d-LHR

< 

* Closing connection 0
* Added cookie __cfduid="d1b47e3eb800370a408899a8eb1473ff41528393358" for domain (nil), path (nil), expire 0
* Added cookie cf_clearance="fcd088a9793d4f63bb89ae0af28d2474839e805f-1528393358-604800" for domain (nil), path (nil), expire 0
* Hostname predb.me was found in DNS cache
*   Trying 104.18.61.235...
* TCP_NODELAY set
* Connected to predb.me (104.18.61.235) port 443 (#1)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL re-using session ID
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=sni188534.cloudflaressl.com
*  start date: May 13 00:00:00 2018 GMT
*  expire date: Nov 19 23:59:59 2018 GMT
*  subjectAltName: host "predb.me" matched cert's "predb.me"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok.
> GET /?search=720p+cat%3A-tv-hd%2C-xxx+-s01*+-s02*+-s03*+-s04*+-s05*+-s06*+-s07*+-s08*+-s09*+-s10*+-s11*+-s12*+-s13*+-s14*+-s15*+-s16*+-s17*+-s18*+-s19*+-s20*+-s21*+-s22*+-s23*+-s24*+-s25*&page=1 HTTP/1.1

Host: predb.me

User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

Accept: */*



< HTTP/1.1 503 Service Temporarily Unavailable

< Date: Thu, 07 Jun 2018 17:42:38 GMT

< Content-Type: text/html; charset=UTF-8

< Transfer-Encoding: chunked

< Connection: close

* Added cookie __cfduid="d063075a6ad9c20c280e08e4c0d37ff3b1528393358" for domain predb.me, path /, expire 1559929358
< Set-Cookie: __cfduid=d063075a6ad9c20c280e08e4c0d37ff3b1528393358; expires=Fri, 07-Jun-19 17:42:38 GMT; path=/; domain=.predb.me; HttpOnly

< X-Frame-Options: SAMEORIGIN

< Cache-Control: no-cache

< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"

< Server: cloudflare

< CF-RAY: 4274ea9a2b5f0a7e-LHR

< 

* Closing connection 1

```

**Comment by KyranRana** [comment] 2018-06-08 16:22
@santah  Can you please send me the code you are using for attempting to bypass cloudflare for this site to ranakyran123@gmail.com ? 

I'll take a look and see where its going wrong. I have PHP 5.5.36 and its working fine for me.

**Comment by santah** [comment] 2018-06-08 17:07
I have pasted it in its entirety here:

https://github.com/KyranRana/cloudflare-bypass/issues/62#issuecomment-394956596

**Comment by KyranRana** [comment] 2018-06-08 17:47
it works for me. Could we do a join.me session? That's the only way i will be able to see what is going on. Email me.

**Comment by santah** [comment] 2018-06-08 18:07
Will do.

**Comment by santah** [comment] 2018-06-08 18:11
Will do.

**Comment by nitemare** [comment] 2018-06-10 00:59
I'm using PHP 7.0.30 and i don't know how to get logs of the request. here is the code i'm using:
`
require_once '../libraries/autoload.php';	
				
use CloudflareBypass\RequestMethod\CFCurl;


$siteUrl = "http://torrentz2.eu/584cb082cb19d81dbabe3e201d89976459d495ea";
//$siteUrl = "http://torrentz2.eu/";
//$siteUrl = "http://google.com/";

$curl_cf_wrapper = new CFCurl(array(
	'cache'         => true,   // Caching now enabled by default; stores clearance tokens in Cache folder
	'max_retries'   => 5       // Max attempts to try and get CF clearance
));
// Get Example: 1
$ch = curl_init($siteUrl);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36');
$site = $curl_cf_wrapper->exec($ch); // Done! NOTE: HEAD requests not supported!
curl_close($ch);
`

**Comment by KyranRana** [comment] 2018-06-12 21:00
nitemare, we can organise a join.me session as well. If you mail me @ ranakyran123@gmail.com I can fix your issue as well.

**Comment by ash121121** [comment] 2018-06-27 00:43
hey mate im also getting this issue. could i join in :D

**Comment by railken** [comment] 2018-06-27 00:59
@KyranRana Did you find the problem?

**Comment by ash121121** [comment] 2018-06-27 09:18
my issue was trying to proxy torrentz2.is ... it would just show the 5 seconds page . but i found changing the proxy ip to  a fresh one solved it.

**Comment by nitemare** [comment] 2018-07-09 16:32
@KyranRana I have not heard back from you, have you made any progress?

**Comment by Dibbyo456** [comment] 2018-08-13 20:12
@KyranRana I'm using PHP 7. The caching is enable by default. But I'm not seeing any cache folder... Help?

**Comment by yumedia** [comment] 2018-08-14 00:35
Same with me, do not see cache folder !

**Comment by KyranRana** [comment] 2018-08-15 12:08
@Dibbyo456 @ash121121 @yumedia Have you all set a custom cache path or are you using the default cache path? The default cache path uses the system's temporary folder (dependent on the OS you use).

**Comment by Dibbyo456** [comment] 2018-08-15 12:13
@KyranRana No. I did not set any custom cache path. I just used the default one.

I just checked /tmp folder on my XAMPP, I could not find any cache..!

**Comment by Dibbyo456** [comment] 2018-08-17 15:11
Update: Just wanted to let you know, that I'm using **CFStreamContext**

**Comment by KyranRana** [comment] 2018-08-17 15:19
Create another PHP file and put the following code inside:
`<?php
echo get_sys_temp_dir();`

Run the file and check in that directory if the cf-bypass folder exists.

**Comment by Dibbyo456** [comment] 2018-08-18 04:42
I think you meant `sys_get_temp_dir()`. Anyway, YES. `cf-bypass` exists.
But an empty folder.. No files.. Is it because I'm _**not using**_ cURL?

**Comment by KyranRana** [comment] 2018-08-18 09:36
1. Try setting a `cache_path` on initialisation and set it to a path you can access on your drive.
2. Run the script and check if a file appears in the path which you have set. The filename should be an MD5 hash.

**Comment by Dibbyo456** [comment] 2018-08-18 10:29
Just like I suspected in the first place.

When, using **CFStreamContext** cache **does not create** at all.
But when **CFCurl** cache creates properly..

**Comment by KyranRana** [comment] 2018-08-21 11:36
I have fixed the caching issue with **CFStreamContext** and added some tests to make sure it continues to work. I will put a pull request out later today.

**Comment by KyranRana** [comment] 2018-08-23 19:29
@railken I am having issues running the tests when creating a pull request, Travis CI build keeps failing but it passes on my local environment. Can you help? Its the only pull request available right now. Thanks.

**Comment by railken** [comment] 2018-08-23 22:57
@KyranRana 

php 5.6: https://github.com/travis-ci/travis-ci/issues/6339
php 7.1.18 and 7.2: a proxy server is necessary

I have created #65 to fix the proxy server with the new CFStreamContext test

When using travis you should add the PROXY_SERVER env var, i have sent to you an email with more details

**Comment by KyranRana** [comment] 2018-08-24 10:29
@railken I haven't received an email from yourself. Also regarding Travis CI, I noticed the travis.yml file has a command to create a .env file however doesn't append any settings to it.

**Comment by railken** [comment] 2018-08-24 10:48
@KyranRana Isn't ranakyran123@gmail.com your email?

btw, add `PROXY_SERVER` as name and `192.244.99.107:3129` as value here
![d](https://i.imgur.com/jWkBT0L.png)

**Comment by KyranRana** [comment] 2018-08-24 12:31
PHP 5.6 test is the only one failing now. The other 2 pass. 

We have to wait for a fix from that thread. :/

**Comment by santah** [comment] 2018-11-10 16:20
As of yesterday, this is no longer working using CFCurl AND CFStreamContext.

(until yesterday, CFStreamContext was working fine).

It now returns 503 error.

No changes on my side.

**Comment by KyranRana** [comment] 2018-11-11 17:13
p

**Comment by KyranRana** [comment] 2018-12-15 12:18
This problem should be resolved. If any of you run into the same problem again. Open a new issue.

**Closed by KyranRana** 2018-12-15 12:18 UTC
